# Generated by Django 3.1.4 on 2020-12-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20201221_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='maxScore',
        ),
        migrations.AddField(
            model_name='user',
            name='max_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
