# Generated by Django 3.1.4 on 2020-12-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=0),
        ),
    ]
