# Generated by Django 3.1.4 on 2021-01-24 15:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dice',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='score_sheet',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
