# Generated by Django 3.1.4 on 2021-01-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210124_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dice',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='score_sheet',
            field=models.JSONField(),
        ),
    ]
